---
run:
  go: '1.23.2'

linters:
  disable-all: false
  enable-all: false
  disable:
    - gci # Doesn't work well with gofumpt.
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint
  fast: false

linters-settings:
  depguard:
    rules:
      main:
        files:
          - '$all'
          - '!$test'
        allow:
          - '$gostd'
          - 'github.com/ypjama/conflictless-keepachangelog/internal/pkg'
          - 'github.com/ypjama/conflictless-keepachangelog/pkg/schema'
          - 'github.com/xeipuuv/gojsonschema'
          - 'gopkg.in/yaml.v3'
      tests:
        files:
          - '$test'
        allow:
          - '$gostd'
          - 'github.com/ypjama/conflictless-keepachangelog/internal/pkg'
          - 'github.com/ypjama/conflictless-keepachangelog/pkg'
          - 'github.com/stretchr/testify/assert'
